spring:
  config:
    import: optional:classpath:tsanet-demo-crash-ssh.properties

tsanet:
  api:
    base-url: "http://localhost:8080"
  auth:
    username: "api@appko.com"
    password: "T123456!"
  storage:
    sqlite-path: "${user.home}/.tsanet-client-demo/data.db"
  cli:
    enabled: false

crash:
  enabled: true
  ssh-port: 2000
  auth-username: crash
  auth-password: crash
