server:
  port: 8090

tsanet:
  demo:
    api-base-url: https://connect2.tsanet.org
    sqlite-path: ${TSANET_DEMO_SQLITE_PATH:${user.home}/.tsanet-demo-ui/data.db}
    username: ${TSANET_DEMO_USERNAME}
    password: ${TSANET_DEMO_PASSWORD}
